version: "3.2"

services:

  mariadb:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - "mariadb-data:/var/lib/mysql"
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  redis:
    image: redis:5-alpine
    restart: always
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  traefik:
    image: traefik:2.2
    restart: always
    command:
      - --log.level=INFO
      - --api=true
      - --api.dashboard=${APP_DEBUG}
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entryPoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
       ACME
      - --certificatesresolvers.primary.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.primary.acme.storage=acme.json
      - --certificatesresolvers.primary.acme.httpchallenge.entrypoint=web
    ports:
      - ${TRAEFIK_HTTP_PORT}:80
      - ${TRAEFIK_HTTPS_PORT}:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      # Uncomment to enable HTTPS via ACME
      - "traefik.http.routers.api.tls.certResolver=primary"
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  seat-web:
    image: eveseat/seat:4
    restart: always
    command: web
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seat-web.rule=Host(`${SEAT_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.seat-web.entrypoints=websecure"
      # Uncomment to enable HTTPS via ACME
      - "traefik.http.routers.seat-web.tls.certResolver=primary"
    depends_on:
      - mariadb
      - redis
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  seat-worker:
    image: eveseat/seat:4
    restart: always
    command: worker
    env_file:
      - .env
    depends_on:
      - seat-web # so that we can get db migrations done
      - mariadb
      - redis
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  seat-cron:
    image: eveseat/seat:4
    restart: always
    command: cron
    env_file:
      - .env
    depends_on:
      - seat-web # so that we can get db migrations done
      - mariadb
      - redis
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  saidthefox.com:
    build:
      context: https://github.com/saidthefox/saidthefox.com.git
      dockerfile: Dockerfile-saidthefox
    container_name: saidthefox.com  
    expose:
     - 80
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.saidthefox.rule=Host(`saidthefox.com`)"
     - "traefik.http.routers.saidthefox.entrypoints=websecure"
  # If you want to enable SSL, uncomment the following line.
     - "traefik.http.routers.saidthefox.tls.certresolver=primary"
    networks:
     - seat-network

  live.js:
    build:
      context: https://github.com/saidthefox/live.saidthefox.com.git
      dockerfile: Dockerfile-livejs
    command: node main.js
    volumes:
      - /usr/app/node_modules
      - /usr/app/html
    ports:
      - "3001:3001"
    networks:
      - seat-network

  live.saidthefox.com:
    build:
      context: https://github.com/saidthefox/live.saidthefox.com-nginx-docker.git
      dockerfile: Dockerfile-live.nginx
    container_name: live.saidthefox.com
    expose:
     - 80
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.live.rule=Host(`live.saidthefox.com`)"
     - "traefik.http.routers.live.entrypoints=websecure"
  # If you want to enable SSL, uncomment the following line.
     - "traefik.http.routers.live.tls.certresolver=primary"
    networks:
     - seat-network

volumes:
    mariadb-data:

networks:
    seat-network:
